### ISSUE TITLE
Tests fail on s390x machines

### ISSUE THREAD

**Issue by guimard** [justjake/quickjs-emscripten#123] opened 2023-11-29 10:34 UTC
Hi,

I'm [Debian Developper](https://qa.debian.org/developer.php?email=yadd%40debian.org) and try to maintain quickjs-emscripten on Debian. When trying to build and test the library on s390x machines (Big Endian), I got the following errors:
```
  103 passing (7s)
  18 failing

  1) QuickJSContext
       QuickJS.newContext
         primitives
           can round-trip a bigint:
     RuntimeError: memory access out of bounds
      at wasm://wasm/0019e9ce:wasm-function[1325]:0x549f3
      at QuickJSFFI.Module._QTS_Call [as QTS_Call] (ts/generated/emscripten-module.WASM_RELEASE_SYNC.js:541:124)
      at /home/yadd/node-quickjs-emscripten/ts/context.js:526:49
      at Lifetime.consume (ts/lifetime.js:61:24)
      at QuickJSContext.callFunction (ts/context.js:526:14)
      at /home/yadd/node-quickjs-emscripten/ts/context.js:286:84
      at Lifetime.consume (ts/lifetime.js:61:24)
      at QuickJSContext.newBigInt (ts/context.js:286:41)
      at Context.<anonymous> (ts/quickjs.test.ts:65:28)
      at callFn (/usr/share/nodejs/mocha/lib/runnable.js:366:21)
      at Test.Runnable.run (/usr/share/nodejs/mocha/lib/runnable.js:354:5)
      at Runner.runTest (/usr/share/nodejs/mocha/lib/runner.js:666:10)
      at /usr/share/nodejs/mocha/lib/runner.js:789:12
      at next (/usr/share/nodejs/mocha/lib/runner.js:581:14)
      at /usr/share/nodejs/mocha/lib/runner.js:591:7
      at next (/usr/share/nodejs/mocha/lib/runner.js:474:14)
      at Immediate._onImmediate (/usr/share/nodejs/mocha/lib/runner.js:559:5)
      at processImmediate (node:internal/timers:471:21)

  2) QuickJSContext
       QuickJS.newContext
         primitives
           can dump a bigint:

      AssertionError [ERR_ASSERTION]: 0n == 18446744073709551616n
      + expected - actual

      -0n
      +18446744073709551616n
      
      at Context.<anonymous> (ts/quickjs.test.ts:73:14)
      at callFn (/usr/share/nodejs/mocha/lib/runnable.js:366:21)
      at Test.Runnable.run (/usr/share/nodejs/mocha/lib/runnable.js:354:5)
      at Runner.runTest (/usr/share/nodejs/mocha/lib/runner.js:666:10)
      at /usr/share/nodejs/mocha/lib/runner.js:789:12
      at next (/usr/share/nodejs/mocha/lib/runner.js:581:14)
      at /usr/share/nodejs/mocha/lib/runner.js:591:7
      at next (/usr/share/nodejs/mocha/lib/runner.js:474:14)
      at Immediate._onImmediate (/usr/share/nodejs/mocha/lib/runner.js:559:5)
      at processImmediate (node:internal/timers:471:21)

  3) QuickJSContext
       QuickJS.newContext
         functions
           can wrap a Javascript function and call it:
     RuntimeError: memory access out of bounds
      at wasm://wasm/0019e9ce:wasm-function[1325]:0x549f3
      at QuickJSFFI.Module._QTS_Call [as QTS_Call] (ts/generated/emscripten-module.WASM_RELEASE_SYNC.js:541:124)
      at /home/yadd/node-quickjs-emscripten/ts/context.js:526:49
      at Lifetime.consume (ts/lifetime.js:61:24)
      at QuickJSContext.callFunction (ts/context.js:526:14)
      at /home/yadd/node-quickjs-emscripten/ts/quickjs.test.ts:139:58
      at Lifetime.consume (ts/lifetime.js:61:24)
      at Context.<anonymous> (ts/quickjs.test.ts:139:38)
      at callFn (/usr/share/nodejs/mocha/lib/runnable.js:366:21)
      at Test.Runnable.run (/usr/share/nodejs/mocha/lib/runnable.js:354:5)
      at Runner.runTest (/usr/share/nodejs/mocha/lib/runner.js:666:10)
      at /usr/share/nodejs/mocha/lib/runner.js:789:12
      at next (/usr/share/nodejs/mocha/lib/runner.js:581:14)
      at /usr/share/nodejs/mocha/lib/runner.js:591:7
      at next (/usr/share/nodejs/mocha/lib/runner.js:474:14)
      at Immediate._onImmediate (/usr/share/nodejs/mocha/lib/runner.js:559:5)
      at processImmediate (node:internal/timers:471:21)

  4) QuickJSContext
       QuickJS.newContext
         "after each" hook for "can wrap a Javascript function and call it":
     RuntimeError: Aborted(Assertion failed: list_empty(&rt->gc_obj_list), at: quickjs/quickjs.c,1983,JS_FreeRuntime). Build with -s ASSERTIONS=1 for more info.
      at abort (ts/generated/emscripten-module.WASM_RELEASE_SYNC.js:309:147)
      at ___assert_fail (ts/generated/emscripten-module.WASM_RELEASE_SYNC.js:387:68)
      at wasm://wasm/0019e9ce:wasm-function[746]:0x30666
      at wasm://wasm/0019e9ce:wasm-function[1083]:0x48f7d
      at QuickJSFFI.Module._QTS_FreeRuntime [as QTS_FreeRuntime] (ts/generated/emscripten-module.WASM_RELEASE_SYNC.js:517:151)
      at Lifetime.disposer (ts/module.js:220:22)
      at Lifetime.dispose (ts/lifetime.js:71:18)
      at Scope.dispose (ts/lifetime.js:220:26)
      at QuickJSRuntime.dispose (ts/runtime.js:124:27)
      at Scope.dispose (ts/lifetime.js:220:26)
      at ContextMemory.dispose (ts/context.js:35:27)
      at QuickJSContext.dispose (ts/context.js:170:21)
      at Context.<anonymous> (ts/quickjs.test.ts:39:8)
      at callFn (/usr/share/nodejs/mocha/lib/runnable.js:366:21)
      at Hook.Runnable.run (/usr/share/nodejs/mocha/lib/runnable.js:354:5)
      at next (/usr/share/nodejs/mocha/lib/runner.js:498:10)
      at Immediate._onImmediate (/usr/share/nodejs/mocha/lib/runner.js:559:5)
      at processImmediate (node:internal/timers:471:21)

  5) QuickJSAsyncContext
       newQuickJSAsyncWASMModule
         sync API
           primitives
             can round-trip a bigint:

      AssertionError [ERR_ASSERTION]: 0n == 18446744073709551616n
      + expected - actual

      -0n
      +18446744073709551616n
      
      at Context.<anonymous> (ts/quickjs.test.ts:66:14)
      at callFn (/usr/share/nodejs/mocha/lib/runnable.js:366:21)
      at Test.Runnable.run (/usr/share/nodejs/mocha/lib/runnable.js:354:5)
      at Runner.runTest (/usr/share/nodejs/mocha/lib/runner.js:666:10)
      at /usr/share/nodejs/mocha/lib/runner.js:789:12
      at next (/usr/share/nodejs/mocha/lib/runner.js:581:14)
      at /usr/share/nodejs/mocha/lib/runner.js:591:7
      at next (/usr/share/nodejs/mocha/lib/runner.js:474:14)
      at Immediate._onImmediate (/usr/share/nodejs/mocha/lib/runner.js:559:5)
      at processImmediate (node:internal/timers:471:21)

  6) QuickJSAsyncContext
       newQuickJSAsyncWASMModule
         sync API
           primitives
             can dump a bigint:

      AssertionError [ERR_ASSERTION]: 0n == 18446744073709551616n
      + expected - actual

      -0n
      +18446744073709551616n
      
      at Context.<anonymous> (ts/quickjs.test.ts:73:14)
      at callFn (/usr/share/nodejs/mocha/lib/runnable.js:366:21)
      at Test.Runnable.run (/usr/share/nodejs/mocha/lib/runnable.js:354:5)
      at Runner.runTest (/usr/share/nodejs/mocha/lib/runner.js:666:10)
      at /usr/share/nodejs/mocha/lib/runner.js:789:12
      at next (/usr/share/nodejs/mocha/lib/runner.js:581:14)
      at /usr/share/nodejs/mocha/lib/runner.js:591:7
      at next (/usr/share/nodejs/mocha/lib/runner.js:474:14)
      at Immediate._onImmediate (/usr/share/nodejs/mocha/lib/runner.js:559:5)
      at processImmediate (node:internal/timers:471:21)

  7) QuickJSAsyncContext
       newQuickJSAsyncWASMModule
         sync API
           functions
             can wrap a Javascript function and call it:
     RuntimeError: memory access out of bounds
      at wasm://wasm/0037a7da:wasm-function[1308]:0xc536c
      at ret.<computed> (ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:490:41)
      at Module._QTS_Call (ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:639:124)
      at QuickJSAsyncFFI.mustBeSync [as QTS_Call] (ts/types-ffi.js:6:24)
      at /home/yadd/node-quickjs-emscripten/ts/context.js:526:49
      at Lifetime.consume (ts/lifetime.js:61:24)
      at QuickJSAsyncContext.callFunction (ts/context.js:526:14)
      at /home/yadd/node-quickjs-emscripten/ts/quickjs.test.ts:139:58
      at Lifetime.consume (ts/lifetime.js:61:24)
      at Context.<anonymous> (ts/quickjs.test.ts:139:38)
      at callFn (/usr/share/nodejs/mocha/lib/runnable.js:366:21)
      at Test.Runnable.run (/usr/share/nodejs/mocha/lib/runnable.js:354:5)
      at Runner.runTest (/usr/share/nodejs/mocha/lib/runner.js:666:10)
      at /usr/share/nodejs/mocha/lib/runner.js:789:12
      at next (/usr/share/nodejs/mocha/lib/runner.js:581:14)
      at /usr/share/nodejs/mocha/lib/runner.js:591:7
      at next (/usr/share/nodejs/mocha/lib/runner.js:474:14)
      at Immediate._onImmediate (/usr/share/nodejs/mocha/lib/runner.js:559:5)
      at processImmediate (node:internal/timers:471:21)

  8) QuickJSAsyncContext
       newQuickJSAsyncWASMModule
         sync API
           functions
             can see its arguments being cloned:

      AssertionError [ERR_ASSERTION]: '0' == 'something'
      + expected - actual

      -0
      +something
      
      at Context.<anonymous> (ts/quickjs.test.ts:194:14)
      at callFn (/usr/share/nodejs/mocha/lib/runnable.js:366:21)
      at Test.Runnable.run (/usr/share/nodejs/mocha/lib/runnable.js:354:5)
      at Runner.runTest (/usr/share/nodejs/mocha/lib/runner.js:666:10)
      at /usr/share/nodejs/mocha/lib/runner.js:789:12
      at next (/usr/share/nodejs/mocha/lib/runner.js:581:14)
      at /usr/share/nodejs/mocha/lib/runner.js:591:7
      at next (/usr/share/nodejs/mocha/lib/runner.js:474:14)
      at Immediate._onImmediate (/usr/share/nodejs/mocha/lib/runner.js:559:5)
      at processImmediate (node:internal/timers:471:21)

  9) QuickJSAsyncContext
       newQuickJSAsyncWASMModule
         sync API
           .newPromise()
             passes an end-to-end test:
     Uncaught RuntimeError: memory access out of bounds
      at wasm://wasm/0037a7da:wasm-function[1308]:0xc536c
      at ret.<computed> (ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:490:41)
      at Module._QTS_Call (ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:639:124)
      at QuickJSAsyncFFI.mustBeSync [as QTS_Call] (ts/types-ffi.js:6:24)
      at /home/yadd/node-quickjs-emscripten/ts/context.js:526:49
      at Lifetime.consume (ts/lifetime.js:61:24)
      at QuickJSAsyncContext.callFunction (ts/context.js:526:14)
      at QuickJSDeferredPromise.resolve (ts/deferred-promise.js:45:44)
      at /home/yadd/node-quickjs-emscripten/ts/quickjs.test.ts:714:85
      at Lifetime.consume (ts/lifetime.js:61:24)
      at /home/yadd/node-quickjs-emscripten/ts/quickjs.test.ts:714:59

  10) QuickJSAsyncContext
       newQuickJSAsyncWASMModule
         sync API
           .resolvePromise()
             retrieves async function return value as a successful VM result:
     RuntimeError: memory access out of bounds
      at wasm://wasm/0037a7da:wasm-function[1308]:0xc536c
      at ret.<computed> (ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:490:41)
      at Module._QTS_Call (ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:639:124)
      at QuickJSAsyncFFI.mustBeSync [as QTS_Call] (ts/types-ffi.js:6:24)
      at /home/yadd/node-quickjs-emscripten/ts/context.js:526:49
      at Lifetime.consume (ts/lifetime.js:61:24)
      at QuickJSAsyncContext.callFunction (ts/context.js:526:14)
      at /home/yadd/node-quickjs-emscripten/ts/context.js:435:25
      at Function.withScope (ts/lifetime.js:160:20)
      at QuickJSAsyncContext.resolvePromise (ts/context.js:432:50)
      at /home/yadd/node-quickjs-emscripten/ts/quickjs.test.ts:753:53
      at Lifetime.consume (ts/lifetime.js:61:24)
      at Context.<anonymous> (ts/quickjs.test.ts:753:30)
      at callFn (/usr/share/nodejs/mocha/lib/runnable.js:366:21)
      at Test.Runnable.run (/usr/share/nodejs/mocha/lib/runnable.js:354:5)
      at Runner.runTest (/usr/share/nodejs/mocha/lib/runner.js:666:10)
      at /usr/share/nodejs/mocha/lib/runner.js:789:12
      at next (/usr/share/nodejs/mocha/lib/runner.js:581:14)
      at /usr/share/nodejs/mocha/lib/runner.js:591:7
      at next (/usr/share/nodejs/mocha/lib/runner.js:474:14)
      at Immediate.<anonymous> (/usr/share/nodejs/mocha/lib/runner.js:559:5)
      at processImmediate (node:internal/timers:471:21)

  11) QuickJSAsyncContext
       newQuickJSAsyncWASMModule
         sync API
           .resolvePromise()
             retrieves async function error as a error VM result:
     RuntimeError: memory access out of bounds
      at wasm://wasm/0037a7da:wasm-function[1308]:0xc536c
      at ret.<computed> (ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:490:41)
      at Module._QTS_Call (ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:639:124)
      at QuickJSAsyncFFI.mustBeSync [as QTS_Call] (ts/types-ffi.js:6:24)
      at /home/yadd/node-quickjs-emscripten/ts/context.js:526:49
      at Lifetime.consume (ts/lifetime.js:61:24)
      at QuickJSAsyncContext.callFunction (ts/context.js:526:14)
      at /home/yadd/node-quickjs-emscripten/ts/context.js:450:40
      at Function.withScope (ts/lifetime.js:160:20)
      at /home/yadd/node-quickjs-emscripten/ts/context.js:441:30
      at new Promise (<anonymous>)
      at QuickJSAsyncContext.resolvePromise (ts/context.js:440:16)
      at /home/yadd/node-quickjs-emscripten/ts/quickjs.test.ts:775:53
      at Lifetime.consume (ts/lifetime.js:61:24)
      at Context.<anonymous> (ts/quickjs.test.ts:775:30)
      at callFn (/usr/share/nodejs/mocha/lib/runnable.js:366:21)
      at Test.Runnable.run (/usr/share/nodejs/mocha/lib/runnable.js:354:5)
      at Runner.runTest (/usr/share/nodejs/mocha/lib/runner.js:666:10)
      at /usr/share/nodejs/mocha/lib/runner.js:789:12
      at next (/usr/share/nodejs/mocha/lib/runner.js:581:14)
      at /usr/share/nodejs/mocha/lib/runner.js:591:7
      at next (/usr/share/nodejs/mocha/lib/runner.js:474:14)
      at Immediate.<anonymous> (/usr/share/nodejs/mocha/lib/runner.js:559:5)
      at processImmediate (node:internal/timers:471:21)

  12) QuickJSAsyncContext
       newQuickJSAsyncWASMModule
         sync API
           .resolvePromise()
             converts non-promise handles into a promise, too:
     RuntimeError: memory access out of bounds
      at wasm://wasm/0037a7da:wasm-function[1308]:0xc536c
      at ret.<computed> (ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:490:41)
      at Module._QTS_Call (ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:639:124)
      at QuickJSAsyncFFI.mustBeSync [as QTS_Call] (ts/types-ffi.js:6:24)
      at /home/yadd/node-quickjs-emscripten/ts/context.js:526:49
      at Lifetime.consume (ts/lifetime.js:61:24)
      at QuickJSAsyncContext.callFunction (ts/context.js:526:14)
      at /home/yadd/node-quickjs-emscripten/ts/context.js:450:40
      at Function.withScope (ts/lifetime.js:160:20)
      at /home/yadd/node-quickjs-emscripten/ts/context.js:441:30
      at new Promise (<anonymous>)
      at QuickJSAsyncContext.resolvePromise (ts/context.js:440:16)
      at Context.<anonymous> (ts/quickjs.test.ts:791:26)
      at callFn (/usr/share/nodejs/mocha/lib/runnable.js:366:21)
      at Test.Runnable.run (/usr/share/nodejs/mocha/lib/runnable.js:354:5)
      at Runner.runTest (/usr/share/nodejs/mocha/lib/runner.js:666:10)
      at /usr/share/nodejs/mocha/lib/runner.js:789:12
      at next (/usr/share/nodejs/mocha/lib/runner.js:581:14)
      at /usr/share/nodejs/mocha/lib/runner.js:591:7
      at next (/usr/share/nodejs/mocha/lib/runner.js:474:14)
      at Immediate.<anonymous> (/usr/share/nodejs/mocha/lib/runner.js:559:5)
      at processImmediate (node:internal/timers:471:21)

  13) QuickJSAsyncContext
       newQuickJSAsyncWASMModule
         async API
           asyncify functions
             sees Promise<handle> as synchronous:
     RuntimeError: Aborted(RuntimeError: unreachable). Build with -s ASSERTIONS=1 for more info.
      at abort (ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:313:147)
      at runAndAbortIfError (ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:468:13)
      at Object.handleSleep (ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:538:21)
      at QuickJSModuleCallbacks.handleAsyncify (ts/module.js:111:29)
      at QuickJSEmscriptenModuleCallbacks.callFunction (ts/module.js:30:80)
      at qts_host_call_function (ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:368:187)
      at wasm://wasm/0037a7da:wasm-function[1226]:0xba96c
      at wasm://wasm/0037a7da:wasm-function[1165]:0xb5d1b
      at wasm://wasm/0037a7da:wasm-function[274]:0x1cee8
      at wasm://wasm/0037a7da:wasm-function[274]:0x1e618
      at wasm://wasm/0037a7da:wasm-function[61]:0x4d71
      at wasm://wasm/0037a7da:wasm-function[780]:0x788dd
      at wasm://wasm/0037a7da:wasm-function[1105]:0xaee12
      at wasm://wasm/0037a7da:wasm-function[830]:0x7eff7
      at wasm://wasm/0037a7da:wasm-function[925]:0x8f362
      at wasm://wasm/0037a7da:wasm-function[1267]:0xbdcee
      at ret.<computed> (ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:490:41)
      at ccall (ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:161:26)
      at QuickJSAsyncFFI.QTS_Eval_MaybeAsync (ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:168:39)
      at /home/yadd/node-quickjs-emscripten/ts/context-asyncify.js:27:51
      at Lifetime.consume (ts/lifetime.js:61:24)
      at QuickJSAsyncContext.evalCodeAsync (ts/context-asyncify.js:27:18)
      at Context.<anonymous> (ts/quickjs.test.ts:844:36)
      at callFn (/usr/share/nodejs/mocha/lib/runnable.js:366:21)
      at Test.Runnable.run (/usr/share/nodejs/mocha/lib/runnable.js:354:5)
      at Runner.runTest (/usr/share/nodejs/mocha/lib/runner.js:666:10)
      at /usr/share/nodejs/mocha/lib/runner.js:789:12
      at next (/usr/share/nodejs/mocha/lib/runner.js:581:14)
      at /usr/share/nodejs/mocha/lib/runner.js:591:7
      at next (/usr/share/nodejs/mocha/lib/runner.js:474:14)
      at Immediate.<anonymous> (/usr/share/nodejs/mocha/lib/runner.js:559:5)
      at processImmediate (node:internal/timers:471:21)

  14) QuickJSAsyncContext
       newQuickJSAsyncWASMModule
         async API
           "after each" hook for "sees Promise<handle> as synchronous":
     RuntimeError: table index is out of bounds
      at wasm://wasm/0037a7da:wasm-function[34]:0x3279
      at wasm://wasm/0037a7da:wasm-function[499]:0x443b3
      at wasm://wasm/0037a7da:wasm-function[732]:0x6fa05
      at wasm://wasm/0037a7da:wasm-function[16]:0xe9b
      at wasm://wasm/0037a7da:wasm-function[1044]:0xa1676
      at ret.<computed> (ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:490:41)
      at QuickJSAsyncFFI.Module._QTS_FreeValuePointer [as QTS_FreeValuePointer] (ts/generated/emscripten-module.WASM_RELEASE_ASYNCIFY.js:618:171)
      at Lifetime.ContextMemory.freeJSValue [as disposer] (ts/context.js:22:22)
      at Lifetime.dispose (ts/lifetime.js:71:18)
      at Scope.dispose (ts/lifetime.js:220:26)
      at ContextMemory.dispose (ts/context.js:35:27)
      at QuickJSAsyncContext.dispose (ts/context.js:170:21)
      at Context.<anonymous> (ts/quickjs.test.ts:828:8)
      at callFn (/usr/share/nodejs/mocha/lib/runnable.js:366:21)
      at Hook.Runnable.run (/usr/share/nodejs/mocha/lib/runnable.js:354:5)
      at next (/usr/share/nodejs/mocha/lib/runner.js:498:10)
      at Immediate._onImmediate (/usr/share/nodejs/mocha/lib/runner.js:559:5)
      at processImmediate (node:internal/timers:471:21)

  15) README.md
       interpreter
         promise example:
     RuntimeError: memory access out of bounds
      at wasm://wasm/0019e9ce:wasm-function[1325]:0x549f3
      at QuickJSFFI.Module._QTS_Call [as QTS_Call] (ts/generated/emscripten-module.WASM_RELEASE_SYNC.js:541:124)
      at /home/yadd/node-quickjs-emscripten/ts/context.js:526:49
      at Lifetime.consume (ts/lifetime.js:61:24)
      at QuickJSContext.callFunction (ts/context.js:526:14)
      at /home/yadd/node-quickjs-emscripten/ts/context.js:435:25
      at Function.withScope (ts/lifetime.js:160:20)
      at QuickJSContext.resolvePromise (ts/context.js:432:50)
      at Context.<anonymous> (ts/readme.test.ts:187:41)
      at callFn (/usr/share/nodejs/mocha/lib/runnable.js:366:21)
      at Test.Runnable.run (/usr/share/nodejs/mocha/lib/runnable.js:354:5)
      at Runner.runTest (/usr/share/nodejs/mocha/lib/runner.js:666:10)
      at /usr/share/nodejs/mocha/lib/runner.js:789:12
      at next (/usr/share/nodejs/mocha/lib/runner.js:581:14)
      at /usr/share/nodejs/mocha/lib/runner.js:591:7
      at next (/usr/share/nodejs/mocha/lib/runner.js:474:14)
      at Immediate.<anonymous> (/usr/share/nodejs/mocha/lib/runner.js:559:5)
      at processImmediate (node:internal/timers:471:21)

  16) README.md
       "after each" hook for "promise example":
     RuntimeError: Aborted(Assertion failed: list_empty(&rt->gc_obj_list), at: quickjs/quickjs.c,1983,JS_FreeRuntime). Build with -s ASSERTIONS=1 for more info.
      at abort (ts/generated/emscripten-module.WASM_RELEASE_SYNC.js:309:147)
      at ___assert_fail (ts/generated/emscripten-module.WASM_RELEASE_SYNC.js:387:68)
      at wasm://wasm/0019e9ce:wasm-function[746]:0x30666
      at wasm://wasm/0019e9ce:wasm-function[1083]:0x48f7d
      at QuickJSFFI.Module._QTS_FreeRuntime [as QTS_FreeRuntime] (ts/generated/emscripten-module.WASM_RELEASE_SYNC.js:517:151)
      at Lifetime.disposer (ts/module.js:220:22)
      at Lifetime.dispose (ts/lifetime.js:71:18)
      at Scope.dispose (ts/lifetime.js:220:26)
      at QuickJSRuntime.dispose (ts/runtime.js:124:27)
      at Scope.dispose (ts/lifetime.js:220:26)
      at ContextMemory.dispose (ts/context.js:35:27)
      at QuickJSContext.dispose (ts/context.js:170:21)
      at /home/yadd/node-quickjs-emscripten/ts/module-test.js:53:19
      at Array.forEach (<anonymous>)
      at TestQuickJSWASMModule.disposeAll (ts/module-test.js:51:24)
      at Context.<anonymous> (ts/readme.test.ts:30:13)
      at callFn (/usr/share/nodejs/mocha/lib/runnable.js:366:21)
      at Hook.Runnable.run (/usr/share/nodejs/mocha/lib/runnable.js:354:5)
      at next (/usr/share/nodejs/mocha/lib/runner.js:498:10)
      at Immediate._onImmediate (/usr/share/nodejs/mocha/lib/runner.js:559:5)
      at processImmediate (node:internal/timers:471:21)

  17) variants
       RELEASE_ASYNC
         has expected build settings:
     Uncaught QuickJSUseAfterFree: Lifetime not alive
      at Lifetime.assertAlive (ts/lifetime.js:80:19)
      at Lifetime.get value [as value] (ts/lifetime.js:40:14)
      at /home/yadd/node-quickjs-emscripten/ts/context.js:250:70
      at Lifetime.consume (ts/lifetime.js:61:24)
      at QuickJSContext.newString (ts/context.js:250:14)
      at Timeout._onTimeout (ts/readme.test.ts:167:32)
      at listOnTimeout (node:internal/timers:564:17)
      at processTimers (node:internal/timers:507:7)

  18) variants
       RELEASE_ASYNC
         has expected build settings:
     Error: done() called multiple times in test <variants RELEASE_ASYNC has expected build settings> of file /home/yadd/node-quickjs-emscripten/ts/variants.test.ts
      at createMultipleDoneError (/usr/share/nodejs/mocha/lib/errors.js:428:13)
      at multiple (/usr/share/nodejs/mocha/lib/runnable.js:290:24)
      at done (/usr/share/nodejs/mocha/lib/runnable.js:301:14)
      at /usr/share/nodejs/mocha/lib/runnable.js:371:11
```

**Comment by justjake** [comment] 2023-12-05 20:18
I'm not familiar with the s390x architecture. Are you compiling the WASM modules yourself? Does Emscripten build other C code correctly on s390x?

**Comment by kungfooman** [comment] 2023-12-07 10:35
Stupid question, but do you need this IBM Z computer to reproduce?

![2021_08_18_IBM_Z_Forest_Z_Custodians_0156_FNL Original-l1-monthly](https://github.com/justjake/quickjs-emscripten/assets/5236548/80c4584e-132a-4076-bd7e-69ad168ea5ef)

**Comment by guimard** [comment] 2023-12-07 10:43
> Stupid question, but do you need this IBM Z computer to reproduce?

Probably but hopefully [Informationstechnikzentrum Bund (ITZBund)](http://www.itzbund.de/) share a virtual machine to us :wink:

**Comment by justjake** [comment] 2024-01-26 21:53
I'm going to close this as it seems the problem is upstream in emscripten and I don't plan to support s390x mainframes

**Closed by justjake** 2024-01-26 21:53 UTC

**Comment by addaleax** [comment] 2024-08-14 13:33
@guimard We were also running into this just now – we were able to resolve the issue, at least for us, by patching the `ModuleMemory` class here to handle Big Endian platforms: https://github.com/justjake/quickjs-emscripten/blob/ad14bdb7a1f23ce29a4b719b182a3cffc392983a/packages/quickjs-emscripten-core/src/memory.ts#L26

Emscripten itself seems to run fine on s390x.

> Stupid question, but do you need this IBM Z computer to reproduce?

No. 🙂 qemu-s390x or docker can do this for you, there are guides for specifically setting up Github actions this way.
